2022-03-07 18:00:23,150 INFO    MainThread:23972 [wandb_setup.py:_flush():75] Loading settings from C:\Users\sophi\.config\wandb\settings
2022-03-07 18:00:23,151 INFO    MainThread:23972 [wandb_setup.py:_flush():75] Loading settings from C:\Users\sophi\SeaIceExtent\SeaIce\wandb\settings
2022-03-07 18:00:23,151 INFO    MainThread:23972 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2022-03-07 18:00:23,151 INFO    MainThread:23972 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'SeaIce\\unet\\tune_hyperparameters.py', 'program': 'C:\\Users\\sophi\\SeaIceExtent\\SeaIce\\unet\\tune_hyperparameters.py'}
2022-03-07 18:00:23,151 INFO    MainThread:23972 [wandb_init.py:_log_setup():386] Logging user logs to C:\Users\sophi\SeaIceExtent\SeaIce\wandb\run-20220307_180023-sjeyzi2k\logs\debug.log
2022-03-07 18:00:23,151 INFO    MainThread:23972 [wandb_init.py:_log_setup():387] Logging internal logs to C:\Users\sophi\SeaIceExtent\SeaIce\wandb\run-20220307_180023-sjeyzi2k\logs\debug-internal.log
2022-03-07 18:00:23,151 INFO    MainThread:23972 [wandb_init.py:init():420] calling init triggers
2022-03-07 18:00:23,152 INFO    MainThread:23972 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-03-07 18:00:23,152 INFO    MainThread:23972 [wandb_init.py:init():471] starting backend
2022-03-07 18:00:23,152 INFO    MainThread:23972 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-03-07 18:00:23,157 INFO    MainThread:23972 [backend.py:ensure_launched():219] starting backend process...
2022-03-07 18:00:23,219 INFO    MainThread:23972 [backend.py:ensure_launched():224] started backend process with pid: 24364
2022-03-07 18:00:23,221 INFO    MainThread:23972 [wandb_init.py:init():480] backend started and connected
2022-03-07 18:00:23,224 INFO    MainThread:23972 [wandb_init.py:init():550] updated telemetry
2022-03-07 18:00:23,367 INFO    MainThread:23972 [wandb_init.py:init():581] communicating current version
2022-03-07 18:00:24,350 INFO    MainThread:23972 [wandb_init.py:init():586] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-07 18:00:24,350 INFO    MainThread:23972 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-07 18:00:54,359 INFO    MainThread:23972 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-03-07 18:00:54,361 ERROR   MainThread:23972 [wandb_init.py:init():601] backend process timed out
2022-03-07 18:00:54,361 ERROR   MainThread:23972 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-03-07 18:00:54,414 ERROR   MainThread:23972 [wandb_init.py:init():978] error
Traceback (most recent call last):
  File "C:\Users\sophi\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 951, in init
    run = wi.init()
  File "C:\Users\sophi\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 614, in init
    backend.cleanup()
  File "C:\Users\sophi\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\backend\backend.py", line 248, in cleanup
    self.interface.join()
  File "C:\Users\sophi\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 458, in join
    super().join()
  File "C:\Users\sophi\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "C:\Users\sophi\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "C:\Users\sophi\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\sophi\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
